### ISSUE TITLE
Touhou 7.5 scaled out of screen in DWM mode

### ISSUE THREAD

**Issue by Jian-Ng** [Raymai97/noborder#3]
I'm on Windows 11, by the way.

I was very glad to find a working (allegedly) application that can run Touhou 7.5 on borderless window mode, unfortunately it does not seem to work, the game screen is incredibly zoomed in, with the excess going off-screen, as shown in [this screenshot](https://imgur.com/a/Oyw1C4Q). I did have DWM formula enabled.

I am aware that DPI settings may be causing the issue, but I have messed around with [these](https://imgur.com/a/w4PN7Ws) options, and the issue still persists.

**Comment by Raymai97** [comment]
Hi @Jian-Ng 

Please try [this release](https://github.com/Raymai97/noborder/releases/download/v1.3.1/noborder.v1.3.1.7z) without any DPI compatibility settings.

![image](https://user-images.githubusercontent.com/3296077/182651138-392465e6-e07e-4b70-8a56-fe5a29d5f585.png)


![image](https://user-images.githubusercontent.com/3296077/182650831-ccada284-22b5-4fad-98f9-04eab8841f26.png)

**Comment by Jian-Ng** [comment]
It is working properly now, thank you very much.
